apiVersion: v1
kind: Namespace
metadata:
  name: lms
  labels:
    name: lms
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lms-server-config
  namespace: lms
data:
  LMS_SERVER_ENV: "production"
  LMS_SERVER_HOST: "0.0.0.0"
  LMS_SERVER_PORT: "8080"
  LMS_LOG_LEVEL: "info"
  LMS_DB_SSLMODE: "require"
  LMS_DB_MAX_IDLE_CONNS: "10"
  LMS_DB_MAX_OPEN_CONNS: "50"
  LMS_DB_CONN_MAX_LIFETIME: "3600"
  LMS_DB_CONN_MAX_IDLE_TIME: "600"
---
apiVersion: v1
kind: Secret
metadata:
  name: lms-server-secrets
  namespace: lms
type: Opaque
stringData:
  JWT_SECRET: "your-jwt-secret-here"
  JWT_REFRESH_SECRET: "your-refresh-secret-here"
  LMS_DB_USER: "postgres"
  LMS_DB_PASSWORD: "postgres"
  LMS_DB_NAME: "lms"
  BUNNY_STREAM_API_KEY: "your-bunny-stream-api-key"
  BUNNY_STREAM_SECURITY_KEY: "your-bunny-stream-security-key"
  BUNNY_STORAGE_API_KEY: "your-bunny-storage-api-key"
  EMAIL_PASSWORD: "your-email-password"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-server
  namespace: lms
  labels:
    app: lms-server
    version: v1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: lms-server
  template:
    metadata:
      labels:
        app: lms-server
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: lms-server
          image: your-registry/lms-server:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: lms-server-config
            - secretRef:
                name: lms-server-secrets
          env:
            - name: DATABASE_URL
              value: "postgresql://$(LMS_DB_USER):$(LMS_DB_PASSWORD)@postgres:5432/$(LMS_DB_NAME)?sslmode=$(LMS_DB_SSLMODE)"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 15"]
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: lms-server
  namespace: lms
  labels:
    app: lms-server
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: lms-server
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lms-server-hpa
  namespace: lms
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lms-server
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30
        - type: Pods
          value: 2
          periodSeconds: 30
      selectPolicy: Max
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lms-server-ingress
  namespace: lms
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "100"
spec:
  tls:
    - hosts:
        - api.yourdomain.com
      secretName: lms-server-tls
  rules:
    - host: api.yourdomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lms-server
                port:
                  number: 8080
